apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devops-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
