server:
  service:
    type: LoadBalancer
    port: 30090
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

serviceAccounts:
  server:
    create: true

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
